### ISSUE TITLE
Not sure why i see this error

### ISSUE THREAD

**Issue by shashi007** [pablojorge/price-tracker#2]
main: http server listening on 5000
main: websocket server created
url.js:90
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url);
    ^

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at new PriceStore (/home/cryptic/Downloads/price-tracker-master/app/models/PriceStore.js:31:24)
    at Function.PriceStore.getInstance (/home/cryptic/Downloads/price-tracker-master/app/models/PriceStore.js:49:31)
    at Object.module.exports.register (/home/cryptic/Downloads/price-tracker-master/app/models/Plugin.js:7:32)
    at Object.module.exports.register (/home/cryptic/Downloads/price-tracker-master/app/plugins/Ambito.js:59:17)
    at /home/cryptic/Downloads/price-tracker-master/server.js:31:20
    at Array.forEach (native)
    at /home/cryptic/Downloads/price-tracker-master/server.js:2

**Comment by phj** [comment]
Hi @shashi007 !

That error was caused by a missing default. The Redis tries to connect to the instance declared in the `REDISCLOUD_URL` environment var. I run the server locally with `heroku local` which reads environment variables from `~/.env`, and in that file, I set the `REDISCLOUD_URL` to a valid [RedisCloud](https://redislabs.com/products/redis-cloud/) connection URL such as "redis://rediscloud:<password>@pub-redis-[...]garantiadata.com:14747".

I just updated the server to connect to 'redis://localhost:6379' by default if no URL is given. You only have to run a Redis instance locally (Docker is the easiest option, see the instructions in the updated README.md)

Hope you can make it work this time!

**Comment by shashi007** [comment]
Thanks! works perfectly now.
